Repository triasteam/StreamNet, pull requests merged in 2019-06, with the labels that each got.

#94 [fix #93] performance upgrade
  src/main/java/com/iota/iri/controllers/TransactionViewModel.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/service/tipselection/impl/CumWeightScore.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/test/java/com/iota/iri/controllers/TransactionViewModelTest.java
  src/test/java/com/iota/iri/service/tipselection/impl/CumWeightScoreTest.java
Labels: Performance（性能提升）

#97 [fix #96] One click performance test
  scripts/iota_perf/PerformanceTestDAG2TM_TPS.jmx
  scripts/iota_perf/check_result.sh
  scripts/iota_perf/nginx.conf
  scripts/iota_perf/run_perf.sh
Labels: test（测试开发）

#100 [fix #99] Genesis forward UT
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/test/java/com/iota/iri/storage/localinmem/LocalInMemoryGraphAlgoTest.java
  src/test/java/com/iota/iri/storage/localinmem/LocalInMemoryGraphStableOrderTest.java
Labels: bug（修复问题）

#51 [fix #50] Support Crypto
  .travis.yml
  pom.xml
  scripts/examples/one_node/cli_conf
  scripts/examples/one_node_batch/cli_conf
  scripts/examples/two_nodes/cli_conf_two_nodes_1
  scripts/examples/two_nodes/cli_conf_two_nodes_2
  scripts/examples/two_nodes_batch/cli_conf_two_nodes_1
  scripts/examples/two_nodes_batch/cli_conf_two_nodes_2
  scripts/iota_api/app.py
  scripts/iota_api/conf
  scripts/iota_cache/iota_cache.py
  scripts/key_manager/README.md
  scripts/key_manager/__init__.py
  scripts/key_manager/signmessage.py
  src/main/java/com/iota/iri/service/API.java
Labels: New Feature（新功能）

#61 [fix #60] add a new document about crypto
  document/crypto/cryptoSimpleIntroduction.md
Labels: document（文档）

#92 [fix #91] add mysql dockerfile about oauth
  scripts/front_end/Dockerfile
  scripts/front_end/entrypoint.sh
  scripts/front_end/run_oauth_docker.sh
  scripts/front_end/trias-oauth/Dockerfile
  scripts/front_end/trias-oauth/create_write.sql
  scripts/front_end/trias-oauth/setup.sh
Labels: DevOps (运维)

#110 [fix #109] Performance test with jmeter README
  scripts/iota_perf/README.md
Labels: bug（修复问题）

#113 [fix #112] Yellow paper add correctness proof
  document/yellow_paper/StreamNet/StreamNet.pdf
  document/yellow_paper/StreamNet/algorithms/genesis_forward.tex
  document/yellow_paper/StreamNet/sections/concepts.tex
  document/yellow_paper/StreamNet/sections/methods.tex
Labels: Paper （论文/白黄皮书）

#101 [fix #83]main.go_add_error_handle
  scripts/front_end/server/main.go
Labels: bug（修复问题）

#111 [fix #95] install nginx and jmeter in travis-ci
  .travis.yml
  scripts/iota_perf/check_result.sh
  scripts/iota_perf/nginx.conf
  scripts/iota_perf/run_perf.sh
Labels: New Feature（新功能）

#98 Add sign up function
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/body/CommonResponse.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/body/request/RegisterOauthRequest.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/body/response/UserInfoVo.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/body/response/UserResourceResponseBody.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/config/LocalConfig.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/config/ResourceServerConfiguration.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/controller/UserController.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/mapper/UserInfoMapper.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/model/Content.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/model/User.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/service/UserService.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/service/impl/UserServiceImpl.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/util/HttpUtils.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/resources/application.yml
  scripts/front_end/trias-oauth/oauth-resource/src/main/resources/db/trias_cli-init.sql
  scripts/front_end/trias-oauth/oauth-resource/src/main/resources/db/trias_cli_user_ddl.sql
  scripts/front_end/trias-oauth/oauth-resource/src/main/resources/mapper/userInfoMapper.xml
  scripts/front_end/trias-oauth/oauth-server/pom.xml
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/body/CommonResponse.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/config/ResourceServerConfiguration.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/config/SecurityConfig.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/config/ServerConfig.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/controller/UserController.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/exception/UserInfoEmptyException.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/mapper/UserDetailsMapper.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/model/Content.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/service/OauthUserService.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/service/UserService.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/service/impl/OauthUserServiceImpl.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/service/impl/UserServiceImpl.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/util/MD5Util.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/util/OauthUtil.java
  scripts/front_end/trias-oauth/oauth-server/src/main/resources/application.yml
  scripts/front_end/trias-oauth/oauth-server/src/main/resources/db/trias-server_ddl.sql
  scripts/front_end/trias-oauth/oauth-server/src/main/resources/mapper/userDetailsMapper.xml
  scripts/front_end/web/config/proxyConfig.js
  scripts/front_end/web/src/common/config/config.js
  scripts/front_end/web/src/main.js
  scripts/front_end/web/src/routes.js
  scripts/front_end/web/src/views/Addition.vue
  scripts/front_end/web/src/views/Home.vue
  scripts/front_end/web/src/views/Login.vue
  scripts/front_end/web/src/views/Register.vue
  scripts/front_end/web/src/views/nav1/Leviatom.vue
  scripts/front_end/web/src/views/nav1/NetCoin.vue
  scripts/front_end/web/src/vuex/store.js
Labels: New Feature（新功能）

#117 [# 91] create a new folder about mysql dockerfile
  scripts/front_end/Dockerfile
  scripts/front_end/run_oauth_docker.sh
  scripts/front_end/trias-oauth/mysql_docker/Dockerfile
  scripts/front_end/trias-oauth/mysql_docker/create_write.sql
  scripts/front_end/trias-oauth/mysql_docker/setup.sh
Labels: bug（修复问题）

#118 [fix #107] QueryNodes query abnormal
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
Labels: bug（修复问题）

#116 [fix #115] utxo persist with genesis forward
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/test/java/com/iota/iri/pluggables/utxo/TransactionDataTest1.java
Labels: bug（修复问题）

#123 [fix #122] add blockmania and hashgraph
  document/yellow_paper/StreamNet/StreamNet.bib
  document/yellow_paper/StreamNet/StreamNet.pdf
  document/yellow_paper/StreamNet/sections/introduction.tex
  src/test/java/com/iota/iri/pluggables/utxo/TransactionDataTest1.java
Labels: Paper （论文/白黄皮书）
