Repository triasteam/StreamNet, pull requests merged in 2019-05, with the labels that each got.

#24 [fix #23] Add v0.2-stream related yellow paper content
  README.md
  document/yellow_paper/StreamNet/StreamNet.aux
  document/yellow_paper/StreamNet/StreamNet.bbl
  document/yellow_paper/StreamNet/StreamNet.bib
  document/yellow_paper/StreamNet/StreamNet.blg
  document/yellow_paper/StreamNet/StreamNet.log
  document/yellow_paper/StreamNet/StreamNet.pdf
  document/yellow_paper/StreamNet/algorithms/genesis_forward.tex
  document/yellow_paper/StreamNet/sections/abstract.tex
  document/yellow_paper/StreamNet/sections/concepts.tex
  document/yellow_paper/StreamNet/sections/introduction.tex
  document/yellow_paper/StreamNet/sections/methods.tex
  scripts/examples/cluster/README.md
Labels: document（文档）

#26 [fix #25]1.Add Deployment page and config;2.Add server platform block
  scripts/front_end/web/src/common/config/config.js
  scripts/front_end/web/src/routes.js
  scripts/front_end/web/src/views/nav2/Deployment.vue
  scripts/front_end/web/src/views/nav2/DevOps.vue
  scripts/front_end/web/src/views/nav2/Experiment.vue
Labels: New Feature（新功能）

#31 [fix #309] optimize network - add three new DatagramPackets and forma…
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/network/UDPReceiver.java
  src/main/java/com/iota/iri/network/replicator/ReplicatorSinkPool.java
  src/main/java/com/iota/iri/network/replicator/ReplicatorSinkProcessor.java
  src/main/java/com/iota/iri/network/replicator/ReplicatorSourceProcessor.java
Labels: Performance（性能提升）

#32 split 'preProcessReceivedData' and add one function to FIFOCache to s…
  src/main/java/com/iota/iri/network/Node.java
Labels: Performance（性能提升）

#36 cherry pick Genesiss forward
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
Labels: duplicate

#35 [fix #309]split process of Transaction out of 'preProcessReceivedData' with 'pr…
  src/main/java/com/iota/iri/network/Node.java
Labels: Performance（性能提升）

#37 [fix #28] Redundant storage in bundleCache
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/service/tipselection/impl/CumWeightScore.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
Labels: bug（修复问题）

#34 [fix #33] store total order to RocksDB
  src/main/java/com/iota/iri/storage/Tangle.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
  src/main/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProvider.java
  src/test/java/com/iota/iri/storage/TangleTest.java
Labels: bug（修复问题）

#38 optimise network - add some processes (not all) when 'optimise-network' is enabled
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/network/UDPReceiver.java
  src/main/java/com/iota/iri/network/replicator/ReplicatorSourceProcessor.java
Labels: Performance（性能提升）

#44 [fix #43] Leviatom Paper
  document/RGui-ggplot2简介.md
  document/yellow_paper/Leviatom/ACM-Reference-Format.bst
  document/yellow_paper/Leviatom/IEEEtran.cls
  document/yellow_paper/Leviatom/Leviatom.bib
  document/yellow_paper/Leviatom/Leviatom.pdf
  document/yellow_paper/Leviatom/Leviatom.tex
  document/yellow_paper/Leviatom/algorithms/tik_tok.tex
  document/yellow_paper/Leviatom/figures/attestation.pdf
  document/yellow_paper/Leviatom/figures/ranking.pdf
  document/yellow_paper/Leviatom/figures/trias.pdf
  document/yellow_paper/Leviatom/sections/abstract.tex
  document/yellow_paper/Leviatom/sections/applications.tex
  document/yellow_paper/Leviatom/sections/introduction.tex
  document/yellow_paper/RGui-ggplot2简介.md
  document/yellow_paper/document.tex
Labels: Paper （论文/白黄皮书）

#42 [fix 41] add cluster deploy and stress test interface
  scripts/examples/cluster/devops_deploy_stress.py
  scripts/examples/cluster/run_stress_test.sh
Labels: DevOps (运维)

#46 [fix old #311]change the logic to skip checking genesis's trunk and branch hash.
  src/main/java/com/iota/iri/validator/TransactionValidator.java
Labels: bug（修复问题）, duplicate

#49 [fix #48] SC review rebuttal
  document/yellow_paper/StreamNet/StreamNet.pdf
  document/yellow_paper/StreamNet/sections/abstract.tex
  document/yellow_paper/StreamNet/sections/concepts.tex
  document/yellow_paper/StreamNet/sections/conclusion.tex
  document/yellow_paper/StreamNet/sections/experiments.tex
  document/yellow_paper/StreamNet/sections/introduction.tex
  document/yellow_paper/StreamNet/sections/methods.tex
Labels: Paper （论文/白黄皮书）

#47 [fix old #309]optimise network -- fill 'preProcessReceivedOptimizedData'
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/network/replicator/ReplicatorSinkProcessor.java
Labels: Performance（性能提升）

#40 [fix #39]Add experiment page;modift some config
  scripts/front_end/web/src/common/config/config.js
  scripts/front_end/web/src/routes.js
  scripts/front_end/web/src/views/nav2/Deployment.vue
  scripts/front_end/web/src/views/nav2/DevOps.vue
  scripts/front_end/web/src/views/nav2/Experiment.vue
Labels: New Feature（新功能）

#53 [fix 41] add portainer readme
  document/iota_deploy/portainer-deploy-info.md
  scripts/examples/cluster/run.sh
  scripts/examples/cluster/run_experiment.sh
  scripts/examples/cluster/run_stress_test.sh
Labels: document（文档）

#57 [fix #56] TRY solidity
  README.md
  document/pictures/StreamNet.png
  scripts/try_solidity/console.sol
  scripts/try_solidity/rps.sol
  scripts/try_solidity/simpleStorage.sol
  scripts/try_solidity/testContract.sol
Labels: New Feature（新功能）

#55 [fix 41] bug fix about stress test interface
  scripts/examples/cluster/devops_deploy_stress.py
  scripts/examples/cluster/run.sh
  scripts/examples/cluster/run_stress_test.sh
Labels: bug（修复问题）

#62 [fix #58] add frontend and portainer deploy link
  README.md
Labels: document（文档）

#54 [fix #30]recovery validate
  scripts/examples/one_node/recovery_one_machine.sh
  scripts/examples/two_nodes/recovery_two_machine.sh
  src/main/java/com/iota/iri/pluggables/utxo/TransactionData.java
Labels: bug（修复问题）

#64 [fix #63]1.Add oauth;2.Add login system
  scripts/front_end/trias-oauth/oauth-resource/pom.xml
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/ResourceApplication.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/body/CommonResponse.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/body/request/OauthLoginRequestBody.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/body/response/UserInfo.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/body/response/UserResourceResponseBody.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/config/LocalConfig.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/config/ResourceServerConfiguration.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/controller/UserController.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/exception/IllegalRoleException.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/exception/OauthNoResposeException.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/exception/UserInfoEmptyException.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/mapper/UserInfoMapper.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/model/Resource.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/model/vo/OauthServerConfig.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/service/UserService.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/service/impl/UserServiceImpl.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/util/MD5Util.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/java/com/trias/resouce/util/OauthUtil.java
  scripts/front_end/trias-oauth/oauth-resource/src/main/resources/application.yml
  scripts/front_end/trias-oauth/oauth-resource/src/main/resources/db/trias_cli-init.sql
  scripts/front_end/trias-oauth/oauth-resource/src/main/resources/logback-spring.xml
  scripts/front_end/trias-oauth/oauth-resource/src/main/resources/mapper/userInfoMapper.xml
  scripts/front_end/trias-oauth/oauth-server/pom.xml
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/TriasOauthApplication.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/body/CommonResponse.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/body/request/RegesterUserRequestBody.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/config/ResourceServerConfiguration.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/config/SecurityConfig.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/config/ServerConfig.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/controller/UserController.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/mapper/UserDetailsMapper.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/model/CustomUserDetails.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/model/LocalUser.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/model/vo/LocalUserRoleVO.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/service/TriasUserDetailsService.java
  scripts/front_end/trias-oauth/oauth-server/src/main/java/com/trias/oauth/service/impl/TriasUserDetailsServiceImpl.java
  scripts/front_end/trias-oauth/oauth-server/src/main/resources/application.yml
  scripts/front_end/trias-oauth/oauth-server/src/main/resources/db/trias_server-init.sql
  scripts/front_end/trias-oauth/oauth-server/src/main/resources/logback-spring.xml
  scripts/front_end/trias-oauth/oauth-server/src/main/resources/mapper/userDetailsMapper.xml
  scripts/front_end/trias-oauth/pom.xml
  scripts/front_end/web/config/index.js
  scripts/front_end/web/package-lock.json
  scripts/front_end/web/package.json
  scripts/front_end/web/src/common/config/config.js
  scripts/front_end/web/src/main.js
  scripts/front_end/web/src/routes.js
  scripts/front_end/web/src/views/Home.vue
  scripts/front_end/web/src/views/Login.vue
  scripts/front_end/web/src/views/nav2/Deployment.vue
  scripts/front_end/web/src/views/nav2/Experiment.vue
  scripts/front_end/web/src/vuex/actions.js
  scripts/front_end/web/src/vuex/store.js
Labels: New Feature（新功能）

#65 [fix #48] new experiment result
  document/yellow_paper/StreamNet/StreamNet.bib
  document/yellow_paper/StreamNet/StreamNet.pdf
  document/yellow_paper/StreamNet/StreamNet.tex
  document/yellow_paper/StreamNet/algorithms/genesis_forward.tex
  document/yellow_paper/StreamNet/algorithms/get_pivot.tex
  document/yellow_paper/StreamNet/algorithms/gossip.tex
  document/yellow_paper/StreamNet/figures/cluster_set_up.pdf
  document/yellow_paper/StreamNet/figures/multi_txn.pdf
  document/yellow_paper/StreamNet/figures/single_txn.pdf
  document/yellow_paper/StreamNet/sections/concepts.tex
  document/yellow_paper/StreamNet/sections/experiments.tex
  document/yellow_paper/StreamNet/sections/introduction.tex
  document/yellow_paper/StreamNet/sections/methods.tex
Labels: Paper （论文/白黄皮书）

#66 [fix #63] modify the readme about leviatom
  README.md
  scripts/front_end/README.md
Labels: document（文档）

#69 [fix #41] bug fix about cluster deploy and stress test
  scripts/examples/cluster/run.sh
  scripts/iota_deploy/server_deploy_batch.py
Labels: bug（修复问题）

#68 [fix #67] get total from memory, not support genesis forward
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
Labels: bug（修复问题）

#78 .travis.yml add install go
  .travis.yml
Labels: bug（修复问题）

#75 [fix #74] StreamNet paper for AFT19
  .travis.yml
  document/yellow_paper/Leviatom/sections/introduction.tex
  document/yellow_paper/StreamNet/StreamNet.bib
  document/yellow_paper/StreamNet/StreamNet.pdf
  document/yellow_paper/StreamNet/figures/multi_txn.pdf
  document/yellow_paper/StreamNet/figures/single_txn.pdf
  document/yellow_paper/StreamNet/sections/experiments.tex
  document/yellow_paper/StreamNet/sections/introduction.tex
Labels: Paper （论文/白黄皮书）

#86 [fix #85] TCP Tweak
  src/main/java/com/iota/iri/network/Node.java
  src/main/java/com/iota/iri/service/API.java
  src/main/java/com/iota/iri/storage/localinmemorygraph/LocalInMemoryGraphProvider.java
Labels: bug（修复问题）

#73 [fix #72] add run_trias.sh
  scripts/trias/run_trias.sh
Labels: DevOps (运维)

#88 [fix #80] only run ci with oraclejdk8
  .travis.yml
Labels: DevOps (运维)

#87 [fix #79] change repo
  scripts/tee/CLI/CLI.go
  scripts/tee/Dockerfile
  scripts/tee/entrypoint.sh
Labels: DevOps (运维), document（文档）

#90 [fix #89] Add Developer link
  README.md
Labels: New Feature（新功能）
